version: 2
updates:
  # Maintain dependencies for Composer.
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "drupal/*"
        dependency-type: all
      - dependency-type: direct
    ignore:
      - dependency-name: "drupal/core-dev"
      - dependency-name: "drupal/core-composer-scaffold"
    commit-message:
      prefix: "Updates "
      include: scope
    target-branch: develop
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10

  # Disable NPM updates.
  - package-ecosystem: npm
    directory: /docroot/themes/custom/themekit
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
    target-branch: develop
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0
